version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech_chalange_fase_1
    container_name: Tech_1_backend
    ports:
      - '3000:3000'
    volumes:
      - ./dist:/app/dist
    command: npm start
    networks:
      - tech_network
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: Tech_1_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=tech1
      - POSTGRES_PASSWORD=tech1@123
      - POSTGRES_DB=tech_fase_1
    networks:
      - tech_network

networks:
  tech_network:
    driver: bridge