version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: tech_fase_1_backend
    container_name: Tech_1_backend  
    ports:
      - '3000:3000'
#    volumes:
#      - ./dist:/app/dist
    command: npm start
    networks:
      - tech_network
    depends_on:
      - db
  
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: tech_fase_1_db
    container_name: Tech_1_db
    ports:
      - '5432:5432'    
    networks:
      - tech_network

networks:
  tech_network:
    driver: bridge