apiVersion: v1
kind: Service
metadata:
  name: tech-backend-service
spec:
  type: NodePort
  selector:
    app: tech-backend
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 31300
# spec:
#  type: NodePort
#  selector: tech-backend
#  ports:
#    - port: 80
#      targetPort: 3000
#      port: 31300
