apiVersion: v1
kind: Pod
metadata:
  name: tech-db-pod
spec:
  containers:
    - name: tech-db-container
      image: rodrigopadilhadossantos/tech_db:1.0.0
      readinessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 10
        periodSeconds: 10
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: db-data
      persistentVolumeClaim:
        claimName: tech-db-pvc
