apiVersion: v1
kind: PersistentVolume
metadata:
  name: tech-db-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/rodrigopadilha/Projetos/FIAP/tech-challange-fase-1/db # Caminho no nรณ do cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-db-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
