name: Deploy API Prod

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build Docker Image And Push top ECR"
    runs-on: ubuntu-latest

    env:
      ECR_REPO_URL: 931751445831.dkr.ecr.us-east-1.amazonaws.com/prod_order-ecr

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Amazon ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Latest ECR Image
        run: |
          cd ../../
          docker build -t prod_order-ecr -f ./docker/Dockerfile.backend .
          echo "Built the latest image to ECR"

          docker tag prod_order-ecr:latest $ECR_REPO_URL:latest

          docker push $ECR_REPO_URL:latest
          echo "Pushed the latest image to ECR"
